name: tm_lib_core
description: .
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_secure_storage: ^4.2.0
  cryptography: ^2.0.1
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  permission_handler: ^7.1.0
  font_awesome_flutter: ^9.1.0
  mobx: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  remove_from_coverage: ^2.0.0
  build_runner: ^2.0.2
  mockito: ^5.0.7
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
