name: tm_lib_core
description: .
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_secure_storage: ^4.2.0
  mobx: ^2.0.1
  flutter_modular: ^3.2.0
  flutter_mobx: ^2.0.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  flutter_svg: ^0.22.0
  google_fonts: 2.1.0
  intl: ^0.17.0
  cpf_cnpj_validator: ^2.0.0
  permission_handler: ^7.1.0
  another_flushbar: 1.10.24
  font_awesome_flutter: ^9.1.0
  json_serializable: ^4.1.4
  dots_indicator: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  remove_from_coverage: ^2.0.0
  build_runner: ^2.0.2
  mockito: ^5.0.7
  mobx_codegen: ^2.0.1+3
  analyzer:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/